### PR TITLE
Readme - English version

### PR DESCRIPTION
**Pull request by Revolution1**
Please merge #15 first

### CODE REVIEW

**Comment by allencloud** [comment]
运海，直接在代码的具体行数，写review会比较好，直接有映射关系。 @hainesc

**Comment by Revolution1** [comment]
@hainesc line 35 is copied from wikipedia, I've fixed the other lines

**Comment by hainesc** [comment]
Please rebase and squash the second commit.

**Comment by hainesc** [comment]
Commit message should be Add English document, not draft.

**Pull request merged**
